---
title: "Ewens - finite site simulation"
output: html_notebook
---

## Load libraries and clear out memory

```{r}
library(phyclust)
library(rstan)
library(tidyverse)
library(ggplot2)

rm(list = ls())

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

## Define utility functions

```{r}
## calculate a harmonic sum: \sum_i 1/i
##
harm_sum <- function(n) {
  k <- 0
  for (i in 1:(n-1)) {
    k <- k + 1/i
  }
  return(k)
}

## Watterson's estimate of theta
##
est_theta_k <- function(seg_sites, n_sample) {
  return(length(seg_sites)/harm_sum(n_sample))
}

## nucleotide diversity estimate of theta
##
est_theta_pi <- function(dna_seqs) {
  n_seqs <- dim(dna_seqs)[1]
  seq_length <- dim(dna_seqs)[2]
  pi <- 0.0 
  for (i in 1:(n_seqs - 1)) {
    for (j in (i+1):n_seqs) {
      pi <- pi + length(seg.sites(dna_seqs[c(i, j), ]))/seq_length
    }
  }
  pi <- pi/(n_seqs*(n_seqs - 1)/2)
  return(pi)
}

## get mean and 95% credible intervals from Stan fit
##
get_fit_stats <- function(fit) {
  fit_dat <- as.data.frame(fit)
  mu <- mean(fit_dat$theta, na.rm = TRUE)
  lo <- quantile(fit_dat$theta, 0.025)
  hi <- quantile(fit_dat$theta, 0.975)
  return(list(mu = mu, lo = lo, hi = hi))
}

## Run the simulation
##
simulate <- function(n_sample, shape, rate, theta, n_rep = 1) {
  theta_k<- numeric(n_rep)
  theta_pi <- numeric(n_rep)
  if (n_rep == 1) {
    theta_bayes <- tibble(rep = 0, theta = 0, lp__ = 0)[0, ]
  } else {
    theta_bayes <- numeric(0)
    theta_lo <- numeric(0)
    theta_hi <- numeric(0)
  }
  for (rep in 1:n_rep) {
    if (n_rep > 1) {
      cat(".")
      if (rep %% 5 == 0) {
        count <- sprintf("%4d", rep)
        cat(count)
      }
      if (rep %% 50 == 0) {
        cat("\n")
      }
    }
    ## simulate the data
    ##
    ms_tree <- phyclust::ms(nsam = n_sample, nreps = 1, opts = paste("-T"))
    ## N.B.: seqs_chr comes back in PHYLIP format as a vector of strings (including the taxon)
    ## 
    seqs_chr <- seqgen(opts = "-mGTR -l1000 -s0.01", rooted.tree = read.tree(text = ms_tree))
    ## We write the result to disk
    ##
    write(seqs_chr, "seqs.phy")
    ## read it back using read.dna (from ape) and delete it
    ##
    tmp <- read.dna("seqs.phy")
    file.remove("seqs.phy")
    ## estimate theta using Watterson approach (theta_k)
    ##
    seg_sites <- seg.sites(tmp)
    theta_k[rep] <- est_theta_k(seg_sites, n_sample)
    ## estimate theta using nucleotide diversity (theta_pi)
    ##
    theta_pi[rep] <- est_theta_pi(tmp)
    ## estimate theta using Bayesian approach
    ##
    a <- numeric(n_sample)
    if (length(seg_sites) > 0) {
      ## convert DNAbin to string for each sample
      ##
      tmp_chr <- character(nrow(tmp))
      for (i in 1:nrow(tmp)) {
        tmp_chr[i] <- paste(as.character(tmp[i, ]), collapse = "")
      }
      ## get counts for each haplotype
      ##
      counts <- table(tmp_chr)
      for (count in 1:length(counts)) {
        index <- counts[count]
        a[index] <- a[index] + 1
      }
    } else {
      a[n_sample] <- 1
    }
    print(a)
    stan_data <- list(N = n_sample,
                      a = a,
                      shape = shape,
                      rate = rate,
                      prior = 0) 
    fit <- stan(file = "ewens.stan",
                data = stan_data,
                refresh = 0)
    if (n_rep == 1) {
      theta_bayes <- add_row(theta_bayes, cbind(rep = rep, as.data.frame(fit)))
    } else {
      tmp <- get_fit_stats(fit)
      theta_bayes <- c(theta_bayes, tmp$mu)
      theta_lo <- c(theta_lo, tmp$lo)
      theta_hi <- c(theta_hi, tmp$hi)
    }
  }
  if (n_rep == 1) {
    return(list(theta_k = theta_k,
                theta_pi = theta_pi,
                theta_bayes = theta_bayes, 
                dna_seq = tmp))
  } else {
    return(list(theta_k = theta_k, 
                theta_pi = theta_pi,
                theta_bayes = theta_bayes,
                theta_lo = theta_lo, 
                theta_hi = theta_hi))
  }
}
```

```{r}
fit <- simulate(25, 1, 1, 0.1)
```